name: infrarisk
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.11.7=py38haa95532_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=22.6.0=py38haa95532_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.9.14=py38haa95532_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - debugpy=1.6.3=py38h885f38d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.0.0=pyhd8ed1ab_0
  - ipykernel=6.15.3=pyh025b116_0
  - ipython=8.5.0=pyh08f2357_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py38haa244fe_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mypy_extensions=0.4.3=py38haa95532_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - openssl=1.1.1q=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=py38haa95532_0
  - pickleshare=0.7.5=py_1003
  - pip=22.1.2=py38haa95532_0
  - platformdirs=2.5.2=py38haa95532_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylint=2.14.5=py38haa95532_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.8.13=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=303=py38h294d835_0
  - pyzmq=23.2.0=py38hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h2bbff1b_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - tomli=2.0.1=py38haa95532_0
  - tomlkit=0.11.1=py38haa95532_0
  - tornado=6.2=py38h294d835_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=py38haa95532_0
  - typing_extensions=4.3.0=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38haa95532_2
  - wrapt=1.14.1=py38h2bbff1b_0
  - zeromq=4.3.4=h0e60522_1
  - pip:
    - affine==2.3.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asgiref==3.5.2
    - attrs==22.1.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - bokeh==2.4.3
    - branca==0.5.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contextily==1.2.0
    - contourpy==1.0.5
    - cryptography==38.0.1
    - cycler==0.11.0
    - cython==0.29.28
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - django==4.1.1
    - docutils==0.19
    - et-xmlfile==1.1.0
    - fastjsonschema==2.16.2
    - fiona==1.8.21
    - folium==0.12.1.post1
    - fonttools==4.37.3
    - gdal==3.4.3
    - gensim==4.2.0
    - geographiclib==1.52
    - geopandas==0.9.0
    - geopy==2.2.0
    - h5py==3.1.0
    - idna==3.4
    - imageio==2.22.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipympl==0.9.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - lxml==4.9.1
    - mapclassify==2.4.3
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - mercantile==1.2.1
    - mistune==2.0.4
    - mock==5.0.0
    - munch==2.5.0
    - nbclient==0.6.8
    - nbconvert==7.0.0
    - nbformat==5.6.1
    - networkx==2.8.6
    - node2vec==0.4.6
    - nose==1.3.7
    - notebook==6.4.12
    - numba==0.56.2
    - numpy==1.23.3
    - openpyxl==3.0.10
    - openquake-engine==3.15.0
    - pandapower==2.6.0
    - pandas==1.5.0
    - pandocfilters==1.5.0
    - path==16.4.0
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.10.0
    - ply==3.11
    - prometheus-client==0.14.1
    - pyaudio==0.2.13
    - pycparser==2.21
    - pygad==2.18.1
    - pygeos==0.12.0
    - pyomo==6.4.4
    - pyproj==3.4.0
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.18.1
    - pysinewave==0.0.6
    - pytz==2022.2.1
    - pywinpty==2.0.8
    - pyyaml==6.0
    - rasterio==1.2.10
    - rbfopt==4.2.5
    - requests==2.28.1
    - rtree==1.0.0
    - scikit-learn==1.1.2
    - scipy==1.6.0
    - seaborn==0.12.0
    - send2trash==1.8.0
    - setuptools==59.8.0
    - shapely==1.8.4
    - smart-open==6.3.0
    - snuggs==1.4.7
    - sounddevice==0.4.5
    - soupsieve==2.3.2.post1
    - sqlparse==0.4.3
    - tenacity==8.1.0
    - terminado==0.16.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - tqdm==4.64.1
    - tzdata==2022.4
    - urllib3==1.26.12
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - wntr==0.4.0
    - xlrd==2.0.1
    - xlsxwriter==3.0.3
    - xyzservices==2022.9.0
    - zipp==3.8.1
prefix: C:\Users\sbalakrishna\Anaconda3\envs\infrarisk
